name: flame_spine
description: Spine component supporter for Flame Engine
version: 0.0.1
homepage: https://github.com/Stark-Industries-Ltd/flame_spine.git

environment:
  sdk: '>=2.18.4 <3.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.4.0
  spine_core:
    git:
      url: https://github.com/Stark-Industries-Ltd/spine_core.git
      ref: main

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0